name: Generic S3 Sync
version: 2.0.0
slug: generic-s3-sync
description: Sync any folder within your Home Assistant to Generis S3 storage
url: https://github.com/iakunin/hass-addons/blob/main/generic-s3-sync
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: manual
init: false
startup: once
advanced: true
hassio_api: true
hassio_role: backup
options:
  sync_paths: []
  s3_access_key: ''
  s3_secret_access_key: ''
  bucket_name: ''
  bucket_region: ''
  endpoint_url: ''
schema:
  sync_paths:
    - str
  s3_access_key: str
  s3_secret_access_key: password
  bucket_name: str
  bucket_region: str
  endpoint_url: str
map:
  - backup:ro
  - media:ro
